

all::
	sh add_mul.sh vol_factor.src.src.V4.0RC1.txt vol_fix_distortion.V4.0RC1-to-RC2.src.txt > vol_factor.src.src.V4.0RC2.txt
	sh mk_vol_factor.src4build.sh vol_factor.src.src.V4.0RC2.txt > vol_factor.src4build.txt

