#!/bin/sh

#
# Setup overtone --- Generate gain1_factor.txt, gain2_factor.txt, vol_factor_effective.txt.
#

CONFIG_FILE=overtone_config.txt

OUTFILE=gain1_factor.txt

echo "#### DO NOT EDIT.  Generated by setup_overtone.sh ####" > $OUTFILE
echo "#"                                                     >> $OUTFILE
echo "# GAIN(db) of filter1(frequency*12)"                   >> $OUTFILE
echo "#            for 200Hz <= frequency"                   >> $OUTFILE
echo "#"                                                     >> $OUTFILE
cat $CONFIG_FILE | awk '{ \
  if ( substr($1,1,1) == "0" || substr($1,1,1) == "1" ) { \
    if ( $2 != "0" ) { \
      printf("%s ",substr($1,5)); \
      split($0,ARR," "); \
      for ( i=5 ; i <= 20 ; i++ ) { \
        if ( i != 5 ) { printf(","); }
        printf("%.2f",$2 * ARR[i]); \
      } \
      printf("\n"); \
    } \
  } \
}'      >> $OUTFILE
echo "" >> $OUTFILE

OUTFILE=gain2_factor.txt

echo "#### DO NOT EDIT.  Generated by setup_overtone.sh ####" > $OUTFILE
echo "#"                                                     >> $OUTFILE
echo "# GAIN(db) for filter2(frequency*26)"                  >> $OUTFILE
echo "#              for frequency < 500Hz"                  >> $OUTFILE
echo "#"                                                     >> $OUTFILE
cat $CONFIG_FILE | awk '{ \
  if ( substr($1,1,1) == "0" || substr($1,1,1) == "1" ) { \
    if ( $3 != "0" ) { \
      printf("%s ",substr($1,5)); \
      split($0,ARR," "); \
      for ( i=5 ; i <= 20 ; i++ ) { \
        if ( i != 5 ) { printf(","); }
        printf("%.2f",$3 * ARR[i]); \
      } \
      printf("\n"); \
    } \
  } \
}'      >> $OUTFILE
echo "" >> $OUTFILE


OUTFILE=vol_factor_effective.txt

echo "#### DO NOT EDIT.  Generated by setup_overtone.sh ####" > $OUTFILE
echo "#"                                                     >> $OUTFILE
echo "# for effective ratio of filter[1,2]."                 >> $OUTFILE
echo "#"                                                     >> $OUTFILE
cat $CONFIG_FILE | awk '{ \
  if ( substr($1,1,1) == "0" || substr($1,1,1) == "1" ) { \
    if ( $2 != "0" || $3 != "0" ) { \
      printf("%s ",$1); \
      split($0,ARR," "); \
      for ( i=5 ; i <= 20 ; i++ ) { \
        if ( i != 5 ) { printf(" "); }
        printf("%.2f",$4 * (1.0 - ARR[i])); \
      } \
      printf("\n"); \
    } \
    else { \
      printf("%s 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00\n",$1); \
    } \
  } \
}'      >> $OUTFILE
echo "" >> $OUTFILE

