#!/bin/sh

#
# Setup overtone --- Generate gain1_factor.txt, gain2_factor.txt, 
#                    gain3_factor.txt and vol_factor_effective.txt.
#

if [ "$3" = "" ]; then
  echo "[USAGE]"
  echo "$0 OVERTONE_CONFIG OVERTONE3_CONFIG BASS_CONFIG"
fi

OVERTONE_CONFIG=$1
OVERTONE3_CONFIG=$2
BASS_CONFIG=$3

echo "setup_overtone: using [$OVERTONE_CONFIG] [$OVERTONE3_CONFIG] [$BASS_CONFIG]"


######## function to merge two param set ########
#
# arg:    input_file
# stdout: output
#
func_merge ()
{

( sort $1 ; echo "" ) | awk '{ \
  if ( NR==1 ) { \
    flg = 0; \
    p0 = match($1, /^[0-1][0-9][0-9]_[A-Z]/); \
    if ( p0 == 1 ) { \
      prev_key=$1; \
      split($0,ARR," "); \
      flg = 1; \
    } \
  } \
  else { \
    p0 = match($1, /^[0-1][0-9][0-9]_[A-Z]/); \
    if ( p0 == 1 ) { \
      split($0,ARR_0," "); \
      if ( prev_key == $1 ) { \
        for ( i=1 ; i <= 16 ; i++ ) { \
          ARR[1+i] = ARR[1+i] + ARR_0[1+i]; \
        } \
        flg = 3; \
      } \
      else { \
        saved=$0; \
        prev_key=$1; \
        flg = 2; \
      } \
    } \
    else { \
      if ( 1 < flg ) { flg = 1; } \
    } \
    if ( flg != 3 ) {
      if ( 0 < flg ) { \
        printf("%s",ARR[1]); \
        for ( i=1 ; i <= 16 ; i++ ) { \
          printf(" %.2f", ARR[1+i]); \
        } \
        printf("\n"); \
      } \
      if ( flg == 2 ) { split(saved,ARR," "); } \
    } \
  } \
}'

}


######## function to output overtone1 params ########
#
# arg:    input_file
# stdout: output
#
func_output_overtone1 ()
{
  cat $1 | awk '{ \
    if ( 0 < match($1, /^[0-1][0-9][0-9]_[A-Z]/) ) { \
      if ( $2 != "0" ) { \
        printf("%s",$1); \
        split($0,ARR," "); \
        idx=1; \
        for ( i=1 ; i <= 16 ; i++ ) { \
          printf(" %.2f",$2 * ARR[4+idx]); \
          if ( 4 + i < length(ARR) ) idx++; \
        } \
        printf("\n"); \
      } \
    } \
  }'
}

######## function to output overtone2 params ########
#
# arg:    input_file
# stdout: output
#
func_output_overtone2 ()
{
  cat $1 | awk '{ \
    if ( 0 < match($1, /^[0-1][0-9][0-9]_[A-Z]/) ) { \
      if ( $3 != "0" ) { \
        printf("%s",$1); \
        split($0,ARR," "); \
        idx=1; \
        for ( i=1 ; i <= 16 ; i++ ) { \
          printf(" %.2f",$3 * ARR[4+idx]); \
          if ( 4 + i < length(ARR) ) idx++; \
        } \
        printf("\n"); \
      } \
    } \
  }'
}


######## OVERTONE 1 ROOT ########

OUTFILE=gain1_root_factor.txt

echo "#### DO NOT EDIT.  Generated by setup_overtone.sh ####" > $OUTFILE
echo "#"                                                     >> $OUTFILE
echo "# GAIN(db) of filter1(frequency*12)"                   >> $OUTFILE
echo "#            for 200Hz <= frequency"                   >> $OUTFILE
echo "#"                                                     >> $OUTFILE

func_output_overtone1 overtone_root.txt >> $OUTFILE


######## OVERTONE 2 ROOT ########

OUTFILE=gain2_root_factor.txt

echo "#### DO NOT EDIT.  Generated by setup_overtone.sh ####" > $OUTFILE
echo "#"                                                     >> $OUTFILE
echo "# GAIN(db) for filter2(frequency*26)"                  >> $OUTFILE
echo "#              for frequency < 500Hz"                  >> $OUTFILE
echo "#"                                                     >> $OUTFILE

func_output_overtone2 overtone_root.txt >> $OUTFILE


######## GAIN0 ########

OUTFILE=gain0_factor.txt

echo "#### DO NOT EDIT.  Generated by setup_overtone.sh ####" > $OUTFILE
echo "#"                                                     >> $OUTFILE
echo "# GAIN(db) of filter1(frequency*0.5)"                  >> $OUTFILE
echo "#             for frequency < 200Hz"                   >> $OUTFILE
echo "#"                                                     >> $OUTFILE

func_output_overtone1 $BASS_CONFIG >> $OUTFILE


######## OVERTONE 1 ########

OUTFILE=gain1_factor.txt

echo "#### DO NOT EDIT.  Generated by setup_overtone.sh ####" > $OUTFILE
echo "#"                                                     >> $OUTFILE
echo "# GAIN(db) of filter1(frequency*12)"                   >> $OUTFILE
echo "#            for 200Hz <= frequency"                   >> $OUTFILE
echo "#"                                                     >> $OUTFILE

func_output_overtone1 $OVERTONE_CONFIG >> $OUTFILE


######## OVERTONE 2 ########

OUTFILE=gain2_factor.txt

echo "#### DO NOT EDIT.  Generated by setup_overtone.sh ####" > $OUTFILE
echo "#"                                                     >> $OUTFILE
echo "# GAIN(db) for filter2(frequency*26)"                  >> $OUTFILE
echo "#              for frequency < 500Hz"                  >> $OUTFILE
echo "#"                                                     >> $OUTFILE

func_output_overtone2 $OVERTONE_CONFIG >> $OUTFILE


######## OVERTONE 3 ########

OUTFILE=gain3_factor.txt

echo "#### DO NOT EDIT.  Generated by setup_overtone.sh ####" > $OUTFILE
echo "#"                                                     >> $OUTFILE
echo "# GAIN(db) of filter3(frequency*4)"                    >> $OUTFILE
echo "#            for 500Hz <= frequency"                   >> $OUTFILE
echo "#"                                                     >> $OUTFILE

func_output_overtone1 $OVERTONE3_CONFIG >> $OUTFILE


######## VOL FACTOR ########

OUTFILE_TMP=_tmp_.txt
OUTFILE=vol_factor_effective.txt

# merge 3 param set
cat overtone_root.txt $OVERTONE_CONFIG $OVERTONE3_CONFIG $BASS_CONFIG | awk '{ \
  p0 = match($1, /^[0-1][0-9][0-9]_[A-Z]/); \
  if ( 0 < p0 ) { \
    if ( $2 != "0" || $3 != "0" ) { \
      printf("%s",$1); \
      split($0,ARR," "); \
      idx=1; \
      for ( i=1 ; i <= 16 ; i++ ) { \
        printf(" %.2f",$4 * ARR[4+idx]); \
        if ( 4 + i < length(ARR) ) idx++; \
      } \
      printf("\n"); \
    } \
    else { \
      printf("%s 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00\n",$1); \
    } \
  } \
}' > $OUTFILE_TMP

echo "#### DO NOT EDIT.  Generated by setup_overtone.sh ####" > $OUTFILE
echo "#"                                                     >> $OUTFILE
echo "# for effective ratio of filter[0,1,2,3]."             >> $OUTFILE
echo "#"                                                     >> $OUTFILE

func_merge $OUTFILE_TMP >> $OUTFILE

